### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by MasonLeffel**

### CODE REVIEW

**Comment by hergin** [comment]
As I said, don't assign it, set a reviewer please!

**Review by AntonThyg — APPROVED** [review]
Code looks good.

**Comment by hergin** [comment]
It looks like you didnt set the number of minimim reviewers to 2. Because without my review, it shouldnt let you merge pull request. I will approve for now.

**Review by hergin — APPROVED** [review]

**Comment by hergin** [comment]
Merge please

**Pull request merged**
